yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
# Импортируем из приложения django.contrib.auth нужный view-класс
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

MAX_LENGTH = 200


class Group(models.Model):
    title = models.CharField(
        max_length=MAX_LENGTH,
        verbose_name='Название группы'
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Ссылка на группу'
    )
    description = models.TextField(verbose_name='Описание группы')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст статьи')
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор статьи'
    )

    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа статей'
    )

    class Meta:
        ordering = ['-pub_date']
        default_related_name = 'posts'

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("text", "group",)
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 7}),
            'group': forms.Select(attrs={'class': 'form-control'})
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from .forms import PostForm
from .models import Post, Group, User
from .utils import paginat


def index(request):
    post_list = Post.objects.all()
    page_obj = paginat(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = page_obj = paginat(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    page_obj = paginat(request, post_list)
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'posts/post_detail.html', {'post': post})


@login_required
def post_create(request):
    form = PostForm(request.POST or None)

    if request.method == 'POST':

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', request.user)
        return render(request, 'posts/create_post.html', {'form': form})
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.user != post.author:
        return redirect('posts:post_detail', post.pk)

    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post.id)

    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.views.generic import CreateView

from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %} Об авторе проекта {% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Привет, я Дмитрий.</h1>
    <p><span style="color:red">Я</span>, разрабатываю проект  на <a href="https://practicum.yandex.ru" target="_blank">Yandex.Practicum</a></p>
    <p>
      Тут я размещу информацию о себе используя свои умения верстать.
      Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста.
    </p>
  </div>  
{% endblock %}

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
  <h1>Вот что я умею</h1>
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
      <li class="list-group-item">
        HTML
      </li>
      <li class="list-group-item">
        CSS
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    <p>Список технологий будет расширятся.</p>
  </article>
  </div>
</div>
{% endblock %}

yatube/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}">
    <title>{% block title %} Последние обновления на сайте {% endblock %}</title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <content>
    {% block content %}
    Контент не подвезли :(
    {% endblock %}
    </content>
    <footer class="border-top text-center py-3">
    {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>                  

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      {% with request.resolver_match.view_name as view_name %} 
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'about:author' %} active{% endif %}" 
            href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %} active{% endif %}" 
            href="{% url 'about:tech' %}">Технологии</a>
        </li>
        <!-- Проверка: авторизован ли пользователь? -->
        {% if user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name  == 'posts:post_create' %} active{% endif %}" 
            href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light{% if view_name  == 'password_change' %} active{% endif %}"
             href="{% url 'password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light{% if view_name  == 'users:login' %} active{% endif %}" 
            href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light{% if view_name  == 'users:signup' %} active{% endif %}"
            href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      {% endwith %}
    </div>
  </nav>

yatube/templates/includes/post_art.html
<article>
  <ul>
    <li>
      Автор: {{  post.author.get_full_name  }}
      {% if author %}
        <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
      {% endif %}
    </li>
    <li>
      Дата публикации: {{  post.pub_date|date:"d E Y" }} 
    </li>
  </ul>
  <p>
    {{  post.text|linebreaks }}</p> 
  </p>
<a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>

{% if post.group and group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы{{ post.group.title }}</a>
{% endif %}
</article>
{% if not forloop.last %}<hr>{% endif %}

yatube/templates/includes/post_error.html
{% if form.errors %}
    {% for field in form %}
    {% for error in field.errors %}            
        <div class="alert alert-danger">
        {{ error|escape }}
        </div>
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        {{ error|escape }}
    </div>
    {% endfor %}
{% endif %}

yatube/templates/includes/post_form.html
<div class="form-group row my-3 p-3">
  <label for="{{ field.id_for_label }}">
    {{ field.label }}
    {% if field.field.required %}
      <span class="required text-danger">*</span>
    {% endif %}
  </label>    
  {{ field }}
  {% if field.help_text %}
    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
      {{ field.help_text|safe }}
    </small>
  {% endif %}
</div>

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}{% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}{% endblock %}
{% block content %}
<div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}Редактировать запись{% else %}Добавить запись{% endif %}             
          </div>
          <div class="card-body">
            {% include 'includes/post_error.html' %}
            <form method="post" action="{{ request.get_full_path }}">
              {% csrf_token %}
            {% for field in form %}
            {% include 'includes/post_form.html' %}
            {% endfor %} 
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html'%}

  {% block title %} Записи сообщества {{ group.title }}{% endblock %}

    {% block content %}
      <div class="container py-5">
        <h1> {{ group.title }} </h1>
        <p>{{ group.description }}</p>
          {% for post in page_obj %}
            {% include "includes/post_art.html" with author=True group=False %}
          {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      </div>  
    {% endblock %}
    

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
    <div class="container py-5">        
        <h1>Все посты</h1>

        {% for post in page_obj %}
            {% include 'includes/post_art.html' with author=True group=True %}
        {% endfor %}

        {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
          </li>
          {% if post.group %}
              <li class="list-group-item">
                  Группа: {{ post.group.title }}
                  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
              </li>
          {% endif %}
          <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
          </li>
          <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        <p>{{ post.text }}</p>
        {% if user.id ==  post.author.id %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            редактировать запись
          </a>
        {% endif %}
      </article>
  </div>
<div class="container py-5">
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя {{  user_obj  }}{% endblock %}
{% block content %}
<div class="container py-5">        
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <h3>Всего постов: {{ author.posts.count }}</h3>
    {% for post in page_obj %}
        {% include "includes/post_art.html" with author=False group=True %}
    {% endfor %}
    
    {% include 'posts/includes/paginator.html' %}
    
</div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:signup' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
        {% load user_filters %} {# Загружаем фильтры #}  
          {# Этот блок будет показан, если в форме есть ошибки #}
          {% include 'includes/post_error.html' %}
          <form method="post" action="{% url 'users:signup' %}"> 
            {% csrf_token %}
          {% for field in form %}
          {% include 'includes/post_form.html' %}
          {% endfor %} 
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}